
name: Stay In Tarkov Build Dispatcher

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'client | launcher| manager | server'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


      - name: Set Client
        if: ${{ github.event.inputs.build == "client" }}
        run: |
          echo "BUILD=client" >> $GITHUB_ENV
          echo "BUILD_DOTNET=" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/StayInTarkov.Client" >> $GITHUB_ENV

      - name: Set Launcher
        if: ${{ github.event.inputs.build == "launcher" }}
        run: |
          echo "BUILD=launcher" >> $GITHUB_ENV
          echo "BUILD_DOTNET=" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Launcher.Classic" >> $GITHUB_ENV

      - name: Set Client
        if: ${{ github.event.inputs.build == "manager" }}
        run: |
          echo "BUILD=manager" >> $GITHUB_ENV
          echo "BUILD_DOTNET=" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Manager" >> $GITHUB_ENV

      - name: Set Server
        if: ${{ github.event.inputs.build == "server" }}
        run: |
          echo "BUILD=server" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Aki-Server-Mod" >> $GITHUB_ENV


      - name: ${{ github.sha }} ${{ $BUILD }}
        run: echo "echo $SETREPO $BUILD_DOTNET"


      - name: Setup dotnet
        if: ${{ BUILD_DOTNET != '' }} 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            ${{ env.BUILD_DOTNET }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ $SETREPO }}

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build
          dotnet test