name: .NET

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
env:
  SolutionName: "StayInTarkov"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release, Debug]
    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout StayInTarkov.Client
      uses: actions/checkout@v4
      with:
        repository: 'StayInTarkov/StayInTarkov.Client'
        path: 'StayInTarkov.Client'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.0.x

    - name: Determine .NET version and build
      run: |
        echo "RSHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        mkdir ${{ github.workspace}}/rls

        for dir in $(find . -name '*.csproj'); do
          cd $(dirname $dir)
          mkdir ${{ github.workspace }}/${{ matrix.configuration }}-build
          dotnet_version=$(grep -Po '<TargetFramework>\K[^<]*' $(basename $dir))
          dotnet restore
          echo "Building $(basename $dir) with .NET version $dotnet_version"
          dotnet build /p:EnableWindowsTargeting=true --configuration ${{ matrix.configuration }} -o ${{ github.workspace }}/${{ matrix.configuration }}-build --no-restore
          mkdir ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}
          mv ${{ github.workspace }}/${{ matrix.configuration }}-build/Assembly-CSharp.dll ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}
          mv ${{ github.workspace }}/${{ matrix.configuration }}-build/StayInTarkov.dll ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}
          zip -jr ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}.zip ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}
          
        done

    # Upload artifact unless its merge to master
    - name: Upload builds to artifacts
      uses: actions/upload-artifact@v3
      if: github.event_name == 'pull_request'
      with:
        name: ${{ env.SolutionName }}-${{ matrix.configuration }}-${{ env.RSHA }}
        path: ${{ env.SolutionName }}-${{ matrix.configuration }}
        if-no-files-found: error

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.master_branch)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.sha }}
        name: Pre-${{ github.sha }}
        draft: true
        prerelease: true
        generate_release_notes: true
        files: ${{ github.workspace }}/${{ env.SolutionName }}-${{ matrix.configuration }}.zip
