
name: Stay In Tarkov Build Dispatcher

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'client | launcher| manager | server'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set Client
        if: ${{ github.event.inputs.build == 'client' }}
        run: |
          echo "BUILD=client" >> $GITHUB_ENV
          echo "BUILD_DOTNET=6.0.x" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/StayInTarkov.Client" >> $GITHUB_ENV

      - name: Set Launcher
        if: ${{ github.event.inputs.build == 'launcher' }}
        run: |
          echo "BUILD=launcher" >> $GITHUB_ENV
          echo "BUILD_DOTNET=8.0.x" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Launcher.Classic" >> $GITHUB_ENV

      - name: Set Manager
        if: ${{ github.event.inputs.build == 'manager' }}
        run: |
          echo "BUILD=manager" >> $GITHUB_ENV
          echo "BUILD_DOTNET=6.0.x" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Manager" >> $GITHUB_ENV

      - name: Set Server
        if: ${{ github.event.inputs.build == 'server' }}
        run: |
          echo "BUILD=server" >> $GITHUB_ENV
          echo "SETREPO=stayintarkov/SIT.Aki-Server-Mod" >> $GITHUB_ENV


      - name: ${{ github.sha }} ${{ env.BUILD }}
        run: echo "${{ env.SETREPO }} + ${{ env.BUILD_DOTNET }}"

      - name: Setup dotnet
        if: ${{ env.BUILD_DOTNET != '' }} 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            ${{ env.BUILD_DOTNET }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SETREPO }}

      - name: Build and Test - dotnet
        if: ${{ env.BUILD_DOTNET != '' }} 
        run: |
          echo ${{ github.repository }}
          pwd
          dotnet restore
          dotnet build
          dotnet test

      - name: Build and Test - server
        if: ${{ env.BUILD == 'server' }} 
        run: |
          echo ${{ github.repository }}
          echo ${{ env.SETREPO }}